// utils/demo.js - Mock data for demo mode (no n8n or Supabase required)

export const DEMO_WORKFLOWS = [
  {
    id: 'demo-wf-001',
    name: 'S3 Backup Automation',
    active: true,
    createdAt: '2025-10-01T10:00:00Z',
    updatedAt: '2025-11-15T14:22:00Z',
    nodes: [{ type: 'n8n-nodes-base.start' }, { type: 'n8n-nodes-base.awsS3' }],
    tags: [{ name: 'aws' }],
  },
  {
    id: 'demo-wf-002',
    name: 'GCP Cloud Run Scaler',
    active: false,
    createdAt: '2025-09-15T09:00:00Z',
    updatedAt: '2025-10-22T08:10:00Z',
    nodes: [{ type: 'n8n-nodes-base.start' }, { type: 'n8n-nodes-base.googleCloudStorage' }],
    tags: [{ name: 'gcp' }],
  },
  {
    id: 'demo-wf-003',
    name: 'Azure Cost Alert Pipeline',
    active: true,
    createdAt: '2025-08-20T11:30:00Z',
    updatedAt: '2025-11-01T16:45:00Z',
    nodes: [{ type: 'n8n-nodes-base.start' }, { type: 'n8n-nodes-base.microsoftAzure' }],
    tags: [{ name: 'azure' }],
  },
  {
    id: 'demo-wf-004',
    name: 'Slack Incident Notifier',
    active: true,
    createdAt: '2025-07-10T14:00:00Z',
    updatedAt: '2025-10-30T12:00:00Z',
    nodes: [{ type: 'n8n-nodes-base.start' }, { type: 'n8n-nodes-base.slack' }],
    tags: [{ name: 'notification' }],
  },
];

export const DEMO_TEMPLATES = [
  {
    id: 'tmpl-001',
    template_id: 'aws-s3-backup',
    name: 'AWS S3 Backup Pipeline',
    description: 'Automate daily backups from local storage to S3 with retention policies and Slack notifications.',
    category: 'AWS Automation',
    tags: ['aws', 'backup', 's3'],
    required_credentials: ['aws'],
    icon: 'fab fa-aws',
  },
  {
    id: 'tmpl-002',
    template_id: 'gcp-cost-monitor',
    name: 'GCP Cost Monitor',
    description: 'Monitor Google Cloud billing and send alerts when costs exceed defined thresholds.',
    category: 'GCP Automation',
    tags: ['gcp', 'billing', 'alerts'],
    required_credentials: ['gcp'],
    icon: 'fab fa-google',
  },
  {
    id: 'tmpl-003',
    template_id: 'azure-vm-scheduler',
    name: 'Azure VM Auto-Scheduler',
    description: 'Automatically start and stop Azure VMs based on schedules to optimize costs.',
    category: 'Azure Automation',
    tags: ['azure', 'vm', 'cost-optimization'],
    required_credentials: ['azure'],
    icon: 'fab fa-microsoft',
  },
  {
    id: 'tmpl-004',
    template_id: 'multi-cloud-health',
    name: 'Multi-Cloud Health Check',
    description: 'Unified health monitoring across AWS, GCP, and Azure with centralized dashboard reporting.',
    category: 'Multi-Cloud',
    tags: ['aws', 'gcp', 'azure', 'monitoring'],
    required_credentials: ['aws', 'gcp', 'azure'],
    icon: 'fas fa-cloud',
  },
];

export const DEMO_CREDENTIALS = [
  {
    id: 'cred-001',
    credential_type: 'aws',
    credential_name: 'AWS Production',
    is_valid: true,
    created_at: '2025-10-01T10:00:00Z',
  },
  {
    id: 'cred-002',
    credential_type: 'gcp',
    credential_name: 'GCP Staging',
    is_valid: true,
    created_at: '2025-09-15T09:00:00Z',
  },
];

export const DEMO_EXECUTIONS = [
  {
    id: 'exec-001',
    n8n_execution_id: 'n8n-exec-001',
    workflow_id: 'demo-wf-001',
    status: 'success',
    started_at: new Date(Date.now() - 3600000).toISOString(),
    finished_at: new Date(Date.now() - 3540000).toISOString(),
    duration_ms: 60000,
  },
  {
    id: 'exec-002',
    n8n_execution_id: 'n8n-exec-002',
    workflow_id: 'demo-wf-003',
    status: 'error',
    error_message: 'Azure API rate limit exceeded',
    started_at: new Date(Date.now() - 7200000).toISOString(),
    finished_at: new Date(Date.now() - 7180000).toISOString(),
    duration_ms: 20000,
  },
];

export const DEMO_TIMELINE = [
  {
    node_name: 'Start',
    node_type: 'trigger',
    status: 'success',
    started_at: new Date(Date.now() - 3600000).toISOString(),
    finished_at: new Date(Date.now() - 3599900).toISOString(),
    duration_ms: 100,
    output_preview: '{ "trigger": "manual" }',
    error: null,
  },
  {
    node_name: 'Fetch S3 Files',
    node_type: 'action',
    status: 'success',
    started_at: new Date(Date.now() - 3599900).toISOString(),
    finished_at: new Date(Date.now() - 3596000).toISOString(),
    duration_ms: 3900,
    output_preview: '{ "files": 142, "totalSize": "2.4GB" }',
    error: null,
  },
  {
    node_name: 'Filter Recent Files',
    node_type: 'action',
    status: 'success',
    started_at: new Date(Date.now() - 3596000).toISOString(),
    finished_at: new Date(Date.now() - 3595200).toISOString(),
    duration_ms: 800,
    output_preview: '{ "filtered": 23 }',
    error: null,
  },
  {
    node_name: 'Upload to Backup Bucket',
    node_type: 'action',
    status: 'success',
    started_at: new Date(Date.now() - 3595200).toISOString(),
    finished_at: new Date(Date.now() - 3542000).toISOString(),
    duration_ms: 53200,
    output_preview: '{ "uploaded": 23, "bytes": 487293847 }',
    error: null,
  },
  {
    node_name: 'Notify Slack',
    node_type: 'action',
    status: 'success',
    started_at: new Date(Date.now() - 3542000).toISOString(),
    finished_at: new Date(Date.now() - 3541500).toISOString(),
    duration_ms: 500,
    output_preview: '{ "message_id": "C01ABC123" }',
    error: null,
  },
];